name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-gradle-tasks:
    uses: ./.github/workflows/gradle-task.yml
    with:
      task: ":app:assembleDebug :app:lint :app:test"
      artifact_name: "ci-build-outputs"
      cache_read_only: true
      timeout_minutes: 60
